### ISSUE TITLE
basic Filesystem usage syntax

### ISSUE THREAD

**Issue by niccolox** [edgurgel/solid#96]
question about basic Filesystem usage

what am I missing for filesystem usage in a simple Phoenix index action below?

```  
def index(conn, _params) do
    template_path = "/lib/app_web/templates/liquid/"
    file_system = Solid.LocalFileSystem.new(template_path)
    text = Solid.LocalFileSystem.full_path(file_system, "hello")
    render(conn, text)
end
```

```
/lib/app_web/templates/liquid/_hello.liquid
hello
```

gives
```
    ** (FunctionClauseError) no function clause matching in String.match?/2
        (elixir 1.12.2) lib/string.ex:2259: String.match?(%Solid.LocalFileSystem{pattern: "_%s.liquid", root: "/lib/app_web/templates/liquid/"}, ~r/^[^.\/][a-zA-Z0-9_\/]+$/)
        (solid 0.10.0) lib/solid/file_system.ex:84: Solid.LocalFileSystem.full_path/2
```

no doubt missing some basic config

**Comment by niccolox** [comment]
cross-posted to Elixir Forum which may be a better venue for this kind of question
https://elixirforum.com/t/solid-filesystem-basic-syntax-help/43589

**Comment by edgurgel** [comment]
Hi @niccolox . I'm not entirely sure what you are trying to achieve here so correct me if I'm wrong.

The `Solid.LocalFileSystem` is meant to be used basically so that the `render` tag can load files. So for example: 

Imagine you have the file "_test.liquid" inside `/tmp`:

```
 $ cat /tmp/_test.liquid
This is the test file!
```

We can then do:

```elixir
file_system = Solid.LocalFileSystem.new("/tmp")
template = "Something {% render 'test' %}"

Solid.parse!(template) |> Solid.render(%{}, [file_system: {Solid.LocalFileSystem, file_system}]) |> IO.puts
```

This should print:

`Something This is the test file!`

We need better docs around this on the README.md I think

----

If what you want is to parse and render liquid files with your code then maybe what you want is something like:

```elixir
text = "lib/app_web/templates/liquid/hello.liquid"
  |> File.read!()
  |> Solid.parse!
  |> Solid.render!(%{})

render(conn, text)
```

Maybe something like this?

**Comment by niccolox** [comment]
I totally get the concepts, what I dont have is a working action for a standard Phoenix index or show controller

I tried to find examples in the docs and on Github and got no complete basic examples

when I try 

```
  def index(conn, _params) do
    text = "lib/folkbot_web/templates/liquid/_hello.liquid"
    |> File.read!()
    |> Solid.parse!
    |> Solid.render!(%{})
    render(conn, text)
  end  
```

I get 

```
Request: GET /
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function Solid.render!/2 is undefined or private
        (solid 0.10.0) Solid.render!(%Solid.Template{parsed_template: [text: ["My name"]]}, %{})
```

totally agree, this is a documentation question

please document a basic index and show action for a Phoenix 1.6 controller using the Filesystem methods

thanks

**Comment by edgurgel** [comment]
Hi @niccolox ! The project doesn't have any intention to be used directly with Phoenix like this but happy to accept wiki pages explaining how to use it if anyone is keen on providing this sort of documentation. Cheers!

**Comment by niccolox** [comment]
I got it working with some hackery

```
  def index(conn, _params) do
    user_email = conn.assigns[:current_user].email
    user_nomnom = "niccolox"
    subdomain = conn.private[:subdomain]
    text = "lib/app_web/templates/liquid/_hello.liquid"
    |> File.read!()
    |> Solid.parse!
    |> Solid.render(%{ "user" => %{ "name" => user_nomnom, "email" => user_email } })
    render(conn, "index.html", 
      text: text,
      subdomain: subdomain)
  end  
```

```_hello.liquid```

```
hello testy
My email is {{ user.email }} 
My name is {{ user.name }}
```

```index.html.heex```

```
<section class="hero is-primary">
  <div class="hero-body">
    <div class="container has-text-centered">
      <p class="title">
        Phoenix Subdomain home page for <%= @subdomain %>
      </p>
      <p class="subtitle">
        <%= @text %>
      </p>
    </div>
  </div>
</section>
```

if I get the Filesystem modules working I'll do a PR

THANKS

**Comment by edgurgel** [comment]
Thanks! That's great!

**Comment by niccolox** [comment]
:+1:

**Comment by niccolox** [comment]
how do I get enumerable into Render?

channels 

```
[
  %App.Channels.Channel{
    updated_at: ~N[2021-11-07 14:49:20],
    is_listed?: nil,
    footer: nil,
    description: nil,
    privacy: nil,
    status: nil,
    is_free?: false,
    contact_id: nil,
    posts: #Ecto.Association.NotLoaded<association :posts is not loaded>,
    about: nil,
    is_published?: nil,
    disclaimer: nil,
    website: #Ecto.Association.NotLoaded<association :website is not loaded>,
    is_suspended?: nil,
    snowflake: nil,
    hosts: #Ecto.Association.NotLoaded<association :hosts is not loaded>,
    name: "niccolox-channel",
    address: nil,
    is_private?: nil,
    __meta__: #Ecto.Schema.Metadata<:loaded, "channels">,
    terms: nil,
    is_invitable?: nil,
    is_featured?: nil,
    creator_id: nil,
    primary_color: nil,
    secondary_color: nil,
    website_id: 1,
    is_previewable?: nil,
    is_subscribable?: nil,
    slug: nil,
    meta_description: nil,
    banner: nil,
    tagline: nil,
    channel_hosts: #Ecto.Association.NotLoaded<association :channel_hosts is not loaded>,
    inserted_at: ~N[2021-11-07 14:49:20],
    id: 1,
    contact: nil,
    owner_id: 1,
    icon: nil
  },
  %App.Channels.Channel{
    updated_at: ~N[2021-11-07 14:49:20],
    is_listed?: nil,
    footer: nil,
    description: nil,
    privacy: nil,
    status: nil,
    is_free?: false,
    contact_id: nil,
    posts: #Ecto.Association.NotLoaded<association :posts is not loaded>,
    about: nil,
    is_published?: nil,
    disclaimer: nil,
    website: #Ecto.Association.NotLoaded<association :website is not loaded>,
    is_suspended?: nil,
    snowflake: nil,
    hosts: #Ecto.Association.NotLoaded<association :hosts is not loaded>,
    name: "free-channel",
    address: nil,
    is_private?: nil,
    __meta__: #Ecto.Schema.Metadata<:loaded, "channels">,
    terms: nil,
    is_invitable?: nil,
    is_featured?: nil,
    creator_id: nil,
    primary_color: nil,
    secondary_color: nil,
    website_id: 1,
    is_previewable?: nil,
    is_subscribable?: nil,
    slug: nil,
    meta_description: nil,
    banner: nil,
    tagline: nil,
    channel_hosts: #Ecto.Association.NotLoaded<association :channel_hosts is not loaded>,
    inserted_at: ~N[2021-11-07 14:49:20],
    id: 2,
    contact: nil,
    owner_id: 1,
    icon: nil
  },
  %App.Channels.Channel{
    updated_at: ~N[2021-11-07 14:49:20],
    is_listed?: nil,
    footer: nil,
    description: nil,
    privacy: nil,
    status: nil,
    is_free?: false,
    contact_id: nil,
    posts: #Ecto.Association.NotLoaded<association :posts is not loaded>,
    about: nil,
    is_published?: nil,
    disclaimer: nil,
    website: #Ecto.Association.NotLoaded<association :website is not loaded>,
    is_suspended?: nil,
    snowflake: nil,
    hosts: #Ecto.Association.NotLoaded<association :hosts is not loaded>,
    name: "countyconservative-channel",
    address: nil,
    is_private?: nil,
    __meta__: #Ecto.Schema.Metadata<:loaded, "channels">,
    terms: nil,
    is_invitable?: nil,
    is_featured?: nil,
    creator_id: nil,
    primary_color: nil,
    secondary_color: nil,
    website_id: 2,
    is_previewable?: nil,
    is_subscribable?: nil,
    slug: nil,
    meta_description: nil,
    banner: nil,
    tagline: nil,
    channel_hosts: #Ecto.Association.NotLoaded<association :channel_hosts is not loaded>,
    inserted_at: ~N[2021-11-07 14:49:20],
    id: 3,
    contact: nil,
    owner_id: 1,
    icon: nil
  },
  %App.Channels.Channel{
    updated_at: ~N[2021-11-07 14:49:20],
    is_listed?: nil,
    footer: nil,
    description: nil,
    privacy: nil,
    status: nil,
    is_free?: false,
    contact_id: nil,
    posts: #Ecto.Association.NotLoaded<association :posts is not loaded>,
    about: nil,
    is_published?: nil,
    disclaimer: nil,
    website: #Ecto.Association.NotLoaded<association :website is not loaded>,
    is_suspended?: nil,
    snowflake: nil,
    hosts: #Ecto.Association.NotLoaded<association :hosts is not loaded>,
    name: "sonoma-channel",
    address: nil,
    is_private?: nil,
    __meta__: #Ecto.Schema.Metadata<:loaded, "channels">,
    terms: nil,
    is_invitable?: nil,
    is_featured?: nil,
    creator_id: nil,
    primary_color: nil,
    secondary_color: nil,
    website_id: 2,
    is_previewable?: nil,
    is_subscribable?: nil,
    slug: nil,
    meta_description: nil,
    banner: nil,
    tagline: nil,
    channel_hosts: #Ecto.Association.NotLoaded<association :channel_hosts is not loaded>,
    inserted_at: ~N[2021-11-07 14:49:20],
    id: 4,
    contact: nil,
    owner_id: 1,
    icon: nil
  }
]
```

```
  def index(conn, _params) do
    user = conn.assigns[:current_user]
    subdomain = conn.private[:subdomain]
    website =  Websites.get_website_from_domain(conn)
    website_name = website.name
    website_domain = website.domain
    website_channels = website.channels
    website_channels_name = "county channel"
    channels = Channels.list_channels()
    IO.puts("DEBUG channels")
    IO.inspect(channels)
    liquid = "lib/app_web/templates/liquid/#{subdomain}/_home.liquid"
    |> File.read!()
    |> Solid.parse!
    |> Solid.render(
      %{ 
        "user" => user, 
        "channels" => ?? , 
        "website" => 
          %{ "name" => website_name, 
             "domain" => website_domain
           }
        }
      )
    render(conn, "index.html", 
      liquid: liquid,
      subdomain: subdomain,
      channels: channels,
      website: website
      )
  end  
```
_hello.liquid
```
channels
{% for channel in channels %}
  {{ channel.name }}
{% endfor %}

```

**Comment by niccolox** [comment]
asked question at Elixir Forum
https://elixirforum.com/t/solid-liquid-templating-basic-for-loop-in-phoenix/43684

**Comment by edgurgel** [comment]
Intersting! Yeah we might want to change Solid to allow people to access data on their structs 🤔 

Here we try to use access (`[]`) the key from map... we might want to call `Map.from_struct` if it's a struct 🤔 or something like this..

**Comment by niccolox** [comment]
I've not used Liquid or Solid before, so am clearly missing a bazillion precursor knowledge items

is what I am trying possible? 
example syntax? 
clues

**Comment by edgurgel** [comment]
Not possible at the moment. Solid doesn't expect structs to be sent for access which I think there is a good argument to allow them to be sent.

This code in particular: https://github.com/edgurgel/solid/blob/main/lib/solid/context.ex#L89-L91

I think we might want to change it so that if it's a struct we call `Map.from_struct(struct)` and then access the data.

**Comment by niccolox** [comment]
```
channels = Channels.list_channels() 
template = "{% for channel in channels %} name {{ channel.name }} {% else %} The collection is empty. {% endfor %}"
{:ok, template} = Solid.parse(template)
Solid.render(template, %{ "channels" => channels }) |> to_string
```
errors

```
channels = Channels.list_channels() 
template = "{% for channel in channels %} name {% else %} The collection is empty. {% endfor %}"
{:ok, template} = Solid.parse(template)
Solid.render(template, %{ "channels" => channels }) |> to_string
gives
" name  name  name  name "
```

so, Solid "sees" the enumerable, but can't access the keys

let me know if I can help, but I am clearly new to this space

**Comment by niccolox** [comment]
Open Question:
What Ecto Repo patterns do work with Enumerables in Solid?

Can I make a non-Phoenix Context generator derived Ecto function and use that data structure to get working ```for``` loop?

**Comment by niccolox** [comment]
> Not possible at the moment. Solid doesn't expect structs to be sent for access which I think there is a good argument to allow them to be sent.
> 
> This code in particular: https://github.com/edgurgel/solid/blob/main/lib/solid/context.ex#L89-L91
> 
> I think we might want to change it so that if it's a struct we call `Map.from_struct(struct)` and then access the data.

hi @edgurgel do you want me to create a New Issue for the updating context to handle enumerables of structs?
